// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: pkg/proto/blobcache/blobcache.proto

package blobcache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blobs_Commit_FullMethodName = "/pkg.proto.blobcache.Blobs/Commit"
)

// BlobsClient is the client API for Blobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobsClient interface {
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type blobsClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobsClient(cc grpc.ClientConnInterface) BlobsClient {
	return &blobsClient{cc}
}

func (c *blobsClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Blobs_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobsServer is the server API for Blobs service.
// All implementations should embed UnimplementedBlobsServer
// for forward compatibility.
type BlobsServer interface {
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
}

// UnimplementedBlobsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobsServer struct{}

func (UnimplementedBlobsServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedBlobsServer) testEmbeddedByValue() {}

// UnsafeBlobsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobsServer will
// result in compilation errors.
type UnsafeBlobsServer interface {
	mustEmbedUnimplementedBlobsServer()
}

func RegisterBlobsServer(s grpc.ServiceRegistrar, srv BlobsServer) {
	// If the following call pancis, it indicates UnimplementedBlobsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blobs_ServiceDesc, srv)
}

func _Blobs_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobsServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blobs_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobsServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blobs_ServiceDesc is the grpc.ServiceDesc for Blobs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blobs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.blobcache.Blobs",
	HandlerType: (*BlobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _Blobs_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/blobcache/blobcache.proto",
}
