// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: google/devtools/build/v1/publish_build_event.proto

package build

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishLifecycleEventRequest_ServiceLevel int32

const (
	PublishLifecycleEventRequest_NONINTERACTIVE PublishLifecycleEventRequest_ServiceLevel = 0
	PublishLifecycleEventRequest_INTERACTIVE    PublishLifecycleEventRequest_ServiceLevel = 1
)

// Enum value maps for PublishLifecycleEventRequest_ServiceLevel.
var (
	PublishLifecycleEventRequest_ServiceLevel_name = map[int32]string{
		0: "NONINTERACTIVE",
		1: "INTERACTIVE",
	}
	PublishLifecycleEventRequest_ServiceLevel_value = map[string]int32{
		"NONINTERACTIVE": 0,
		"INTERACTIVE":    1,
	}
)

func (x PublishLifecycleEventRequest_ServiceLevel) Enum() *PublishLifecycleEventRequest_ServiceLevel {
	p := new(PublishLifecycleEventRequest_ServiceLevel)
	*p = x
	return p
}

func (x PublishLifecycleEventRequest_ServiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishLifecycleEventRequest_ServiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_google_devtools_build_v1_publish_build_event_proto_enumTypes[0].Descriptor()
}

func (PublishLifecycleEventRequest_ServiceLevel) Type() protoreflect.EnumType {
	return &file_google_devtools_build_v1_publish_build_event_proto_enumTypes[0]
}

func (x PublishLifecycleEventRequest_ServiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishLifecycleEventRequest_ServiceLevel.Descriptor instead.
func (PublishLifecycleEventRequest_ServiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP(), []int{0, 0}
}

type PublishLifecycleEventRequest struct {
	state                                protoimpl.MessageState                    `protogen:"open.v1"`
	ServiceLevel                         PublishLifecycleEventRequest_ServiceLevel `protobuf:"varint,1,opt,name=service_level,json=serviceLevel,proto3,enum=google.devtools.build.v1.PublishLifecycleEventRequest_ServiceLevel" json:"service_level,omitempty"`
	BuildEvent                           *OrderedBuildEvent                        `protobuf:"bytes,2,opt,name=build_event,json=buildEvent,proto3" json:"build_event,omitempty"`
	StreamTimeout                        *durationpb.Duration                      `protobuf:"bytes,3,opt,name=stream_timeout,json=streamTimeout,proto3" json:"stream_timeout,omitempty"`
	NotificationKeywords                 []string                                  `protobuf:"bytes,4,rep,name=notification_keywords,json=notificationKeywords,proto3" json:"notification_keywords,omitempty"`
	ProjectId                            string                                    `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CheckPrecedingLifecycleEventsPresent bool                                      `protobuf:"varint,7,opt,name=check_preceding_lifecycle_events_present,json=checkPrecedingLifecycleEventsPresent,proto3" json:"check_preceding_lifecycle_events_present,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PublishLifecycleEventRequest) Reset() {
	*x = PublishLifecycleEventRequest{}
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishLifecycleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishLifecycleEventRequest) ProtoMessage() {}

func (x *PublishLifecycleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishLifecycleEventRequest.ProtoReflect.Descriptor instead.
func (*PublishLifecycleEventRequest) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP(), []int{0}
}

func (x *PublishLifecycleEventRequest) GetServiceLevel() PublishLifecycleEventRequest_ServiceLevel {
	if x != nil {
		return x.ServiceLevel
	}
	return PublishLifecycleEventRequest_NONINTERACTIVE
}

func (x *PublishLifecycleEventRequest) GetBuildEvent() *OrderedBuildEvent {
	if x != nil {
		return x.BuildEvent
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetStreamTimeout() *durationpb.Duration {
	if x != nil {
		return x.StreamTimeout
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetNotificationKeywords() []string {
	if x != nil {
		return x.NotificationKeywords
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PublishLifecycleEventRequest) GetCheckPrecedingLifecycleEventsPresent() bool {
	if x != nil {
		return x.CheckPrecedingLifecycleEventsPresent
	}
	return false
}

type PublishBuildToolEventStreamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishBuildToolEventStreamResponse) Reset() {
	*x = PublishBuildToolEventStreamResponse{}
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBuildToolEventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBuildToolEventStreamResponse) ProtoMessage() {}

func (x *PublishBuildToolEventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBuildToolEventStreamResponse.ProtoReflect.Descriptor instead.
func (*PublishBuildToolEventStreamResponse) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP(), []int{1}
}

func (x *PublishBuildToolEventStreamResponse) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *PublishBuildToolEventStreamResponse) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type OrderedBuildEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Event          *BuildEvent            `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderedBuildEvent) Reset() {
	*x = OrderedBuildEvent{}
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderedBuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderedBuildEvent) ProtoMessage() {}

func (x *OrderedBuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderedBuildEvent.ProtoReflect.Descriptor instead.
func (*OrderedBuildEvent) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP(), []int{2}
}

func (x *OrderedBuildEvent) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *OrderedBuildEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *OrderedBuildEvent) GetEvent() *BuildEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishBuildToolEventStreamRequest struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	OrderedBuildEvent                    *OrderedBuildEvent     `protobuf:"bytes,4,opt,name=ordered_build_event,json=orderedBuildEvent,proto3" json:"ordered_build_event,omitempty"`
	NotificationKeywords                 []string               `protobuf:"bytes,5,rep,name=notification_keywords,json=notificationKeywords,proto3" json:"notification_keywords,omitempty"`
	ProjectId                            string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CheckPrecedingLifecycleEventsPresent bool                   `protobuf:"varint,7,opt,name=check_preceding_lifecycle_events_present,json=checkPrecedingLifecycleEventsPresent,proto3" json:"check_preceding_lifecycle_events_present,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PublishBuildToolEventStreamRequest) Reset() {
	*x = PublishBuildToolEventStreamRequest{}
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBuildToolEventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBuildToolEventStreamRequest) ProtoMessage() {}

func (x *PublishBuildToolEventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_publish_build_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBuildToolEventStreamRequest.ProtoReflect.Descriptor instead.
func (*PublishBuildToolEventStreamRequest) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBuildToolEventStreamRequest) GetOrderedBuildEvent() *OrderedBuildEvent {
	if x != nil {
		return x.OrderedBuildEvent
	}
	return nil
}

func (x *PublishBuildToolEventStreamRequest) GetNotificationKeywords() []string {
	if x != nil {
		return x.NotificationKeywords
	}
	return nil
}

func (x *PublishBuildToolEventStreamRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PublishBuildToolEventStreamRequest) GetCheckPrecedingLifecycleEventsPresent() bool {
	if x != nil {
		return x.CheckPrecedingLifecycleEventsPresent
	}
	return false
}

var File_google_devtools_build_v1_publish_build_event_proto protoreflect.FileDescriptor

const file_google_devtools_build_v1_publish_build_event_proto_rawDesc = "" +
	"\n" +
	"2google/devtools/build/v1/publish_build_event.proto\x12\x18google.devtools.build.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a+google/devtools/build/v1/build_events.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x04\n" +
	"\x1cPublishLifecycleEventRequest\x12h\n" +
	"\rservice_level\x18\x01 \x01(\x0e2C.google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevelR\fserviceLevel\x12Q\n" +
	"\vbuild_event\x18\x02 \x01(\v2+.google.devtools.build.v1.OrderedBuildEventB\x03\xe0A\x02R\n" +
	"buildEvent\x12@\n" +
	"\x0estream_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rstreamTimeout\x123\n" +
	"\x15notification_keywords\x18\x04 \x03(\tR\x14notificationKeywords\x12\"\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tB\x03\xe0A\x02R\tprojectId\x12V\n" +
	"(check_preceding_lifecycle_events_present\x18\a \x01(\bR$checkPrecedingLifecycleEventsPresent\"3\n" +
	"\fServiceLevel\x12\x12\n" +
	"\x0eNONINTERACTIVE\x10\x00\x12\x0f\n" +
	"\vINTERACTIVE\x10\x01\"\x8f\x01\n" +
	"#PublishBuildToolEventStreamResponse\x12?\n" +
	"\tstream_id\x18\x01 \x01(\v2\".google.devtools.build.v1.StreamIdR\bstreamId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\"\xb9\x01\n" +
	"\x11OrderedBuildEvent\x12?\n" +
	"\tstream_id\x18\x01 \x01(\v2\".google.devtools.build.v1.StreamIdR\bstreamId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12:\n" +
	"\x05event\x18\x03 \x01(\v2$.google.devtools.build.v1.BuildEventR\x05event\"\xb7\x02\n" +
	"\"PublishBuildToolEventStreamRequest\x12`\n" +
	"\x13ordered_build_event\x18\x04 \x01(\v2+.google.devtools.build.v1.OrderedBuildEventB\x03\xe0A\x02R\x11orderedBuildEvent\x123\n" +
	"\x15notification_keywords\x18\x05 \x03(\tR\x14notificationKeywords\x12\"\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tB\x03\xe0A\x02R\tprojectId\x12V\n" +
	"(check_preceding_lifecycle_events_present\x18\a \x01(\bR$checkPrecedingLifecycleEventsPresent2\xde\x04\n" +
	"\x11PublishBuildEvent\x12\xc9\x01\n" +
	"\x15PublishLifecycleEvent\x126.google.devtools.build.v1.PublishLifecycleEventRequest\x1a\x16.google.protobuf.Empty\"`\x82\xd3\xe4\x93\x02Z:\x01*Z :\x01*\"\x1b/v1/lifecycleEvents:publish\"3/v1/projects/{project_id=*}/lifecycleEvents:publish\x12\xa6\x02\n" +
	"\x1bPublishBuildToolEventStream\x12<.google.devtools.build.v1.PublishBuildToolEventStreamRequest\x1a=.google.devtools.build.v1.PublishBuildToolEventStreamResponse\"\x85\x01\xdaA4ordered_build_event,notification_keywords,project_id\x82\xd3\xe4\x93\x02H:\x01*Z\x17:\x01*\"\x12/v1/events:publish\"*/v1/projects/{project_id=*}/events:publish(\x010\x01\x1aT\xcaA buildeventservice.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\x88\x01\n" +
	"\x1ccom.google.devtools.build.v1B\fBackendProtoP\x01Z=google.golang.org/genproto/googleapis/devtools/build/v1;build\xf8\x01\x01\xca\x02\x15Google\\Cloud\\Build\\V1b\x06proto3"

var (
	file_google_devtools_build_v1_publish_build_event_proto_rawDescOnce sync.Once
	file_google_devtools_build_v1_publish_build_event_proto_rawDescData []byte
)

func file_google_devtools_build_v1_publish_build_event_proto_rawDescGZIP() []byte {
	file_google_devtools_build_v1_publish_build_event_proto_rawDescOnce.Do(func() {
		file_google_devtools_build_v1_publish_build_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_devtools_build_v1_publish_build_event_proto_rawDesc), len(file_google_devtools_build_v1_publish_build_event_proto_rawDesc)))
	})
	return file_google_devtools_build_v1_publish_build_event_proto_rawDescData
}

var file_google_devtools_build_v1_publish_build_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_devtools_build_v1_publish_build_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_devtools_build_v1_publish_build_event_proto_goTypes = []any{
	(PublishLifecycleEventRequest_ServiceLevel)(0), // 0: google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevel
	(*PublishLifecycleEventRequest)(nil),           // 1: google.devtools.build.v1.PublishLifecycleEventRequest
	(*PublishBuildToolEventStreamResponse)(nil),    // 2: google.devtools.build.v1.PublishBuildToolEventStreamResponse
	(*OrderedBuildEvent)(nil),                      // 3: google.devtools.build.v1.OrderedBuildEvent
	(*PublishBuildToolEventStreamRequest)(nil),     // 4: google.devtools.build.v1.PublishBuildToolEventStreamRequest
	(*durationpb.Duration)(nil),                    // 5: google.protobuf.Duration
	(*StreamId)(nil),                               // 6: google.devtools.build.v1.StreamId
	(*BuildEvent)(nil),                             // 7: google.devtools.build.v1.BuildEvent
	(*emptypb.Empty)(nil),                          // 8: google.protobuf.Empty
}
var file_google_devtools_build_v1_publish_build_event_proto_depIdxs = []int32{
	0, // 0: google.devtools.build.v1.PublishLifecycleEventRequest.service_level:type_name -> google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevel
	3, // 1: google.devtools.build.v1.PublishLifecycleEventRequest.build_event:type_name -> google.devtools.build.v1.OrderedBuildEvent
	5, // 2: google.devtools.build.v1.PublishLifecycleEventRequest.stream_timeout:type_name -> google.protobuf.Duration
	6, // 3: google.devtools.build.v1.PublishBuildToolEventStreamResponse.stream_id:type_name -> google.devtools.build.v1.StreamId
	6, // 4: google.devtools.build.v1.OrderedBuildEvent.stream_id:type_name -> google.devtools.build.v1.StreamId
	7, // 5: google.devtools.build.v1.OrderedBuildEvent.event:type_name -> google.devtools.build.v1.BuildEvent
	3, // 6: google.devtools.build.v1.PublishBuildToolEventStreamRequest.ordered_build_event:type_name -> google.devtools.build.v1.OrderedBuildEvent
	1, // 7: google.devtools.build.v1.PublishBuildEvent.PublishLifecycleEvent:input_type -> google.devtools.build.v1.PublishLifecycleEventRequest
	4, // 8: google.devtools.build.v1.PublishBuildEvent.PublishBuildToolEventStream:input_type -> google.devtools.build.v1.PublishBuildToolEventStreamRequest
	8, // 9: google.devtools.build.v1.PublishBuildEvent.PublishLifecycleEvent:output_type -> google.protobuf.Empty
	2, // 10: google.devtools.build.v1.PublishBuildEvent.PublishBuildToolEventStream:output_type -> google.devtools.build.v1.PublishBuildToolEventStreamResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_google_devtools_build_v1_publish_build_event_proto_init() }
func file_google_devtools_build_v1_publish_build_event_proto_init() {
	if File_google_devtools_build_v1_publish_build_event_proto != nil {
		return
	}
	file_google_devtools_build_v1_build_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_devtools_build_v1_publish_build_event_proto_rawDesc), len(file_google_devtools_build_v1_publish_build_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_devtools_build_v1_publish_build_event_proto_goTypes,
		DependencyIndexes: file_google_devtools_build_v1_publish_build_event_proto_depIdxs,
		EnumInfos:         file_google_devtools_build_v1_publish_build_event_proto_enumTypes,
		MessageInfos:      file_google_devtools_build_v1_publish_build_event_proto_msgTypes,
	}.Build()
	File_google_devtools_build_v1_publish_build_event_proto = out.File
	file_google_devtools_build_v1_publish_build_event_proto_goTypes = nil
	file_google_devtools_build_v1_publish_build_event_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PublishBuildEventClient is the client API for PublishBuildEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublishBuildEventClient interface {
	PublishLifecycleEvent(ctx context.Context, in *PublishLifecycleEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublishBuildToolEventStream(ctx context.Context, opts ...grpc.CallOption) (PublishBuildEvent_PublishBuildToolEventStreamClient, error)
}

type publishBuildEventClient struct {
	cc grpc.ClientConnInterface
}

func NewPublishBuildEventClient(cc grpc.ClientConnInterface) PublishBuildEventClient {
	return &publishBuildEventClient{cc}
}

func (c *publishBuildEventClient) PublishLifecycleEvent(ctx context.Context, in *PublishLifecycleEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/google.devtools.build.v1.PublishBuildEvent/PublishLifecycleEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publishBuildEventClient) PublishBuildToolEventStream(ctx context.Context, opts ...grpc.CallOption) (PublishBuildEvent_PublishBuildToolEventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PublishBuildEvent_serviceDesc.Streams[0], "/google.devtools.build.v1.PublishBuildEvent/PublishBuildToolEventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &publishBuildEventPublishBuildToolEventStreamClient{stream}
	return x, nil
}

type PublishBuildEvent_PublishBuildToolEventStreamClient interface {
	Send(*PublishBuildToolEventStreamRequest) error
	Recv() (*PublishBuildToolEventStreamResponse, error)
	grpc.ClientStream
}

type publishBuildEventPublishBuildToolEventStreamClient struct {
	grpc.ClientStream
}

func (x *publishBuildEventPublishBuildToolEventStreamClient) Send(m *PublishBuildToolEventStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *publishBuildEventPublishBuildToolEventStreamClient) Recv() (*PublishBuildToolEventStreamResponse, error) {
	m := new(PublishBuildToolEventStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PublishBuildEventServer is the server API for PublishBuildEvent service.
type PublishBuildEventServer interface {
	PublishLifecycleEvent(context.Context, *PublishLifecycleEventRequest) (*emptypb.Empty, error)
	PublishBuildToolEventStream(PublishBuildEvent_PublishBuildToolEventStreamServer) error
}

// UnimplementedPublishBuildEventServer can be embedded to have forward compatible implementations.
type UnimplementedPublishBuildEventServer struct {
}

func (*UnimplementedPublishBuildEventServer) PublishLifecycleEvent(context.Context, *PublishLifecycleEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishLifecycleEvent not implemented")
}
func (*UnimplementedPublishBuildEventServer) PublishBuildToolEventStream(PublishBuildEvent_PublishBuildToolEventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PublishBuildToolEventStream not implemented")
}

func RegisterPublishBuildEventServer(s *grpc.Server, srv PublishBuildEventServer) {
	s.RegisterService(&_PublishBuildEvent_serviceDesc, srv)
}

func _PublishBuildEvent_PublishLifecycleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishLifecycleEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishBuildEventServer).PublishLifecycleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.devtools.build.v1.PublishBuildEvent/PublishLifecycleEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishBuildEventServer).PublishLifecycleEvent(ctx, req.(*PublishLifecycleEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublishBuildEvent_PublishBuildToolEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublishBuildEventServer).PublishBuildToolEventStream(&publishBuildEventPublishBuildToolEventStreamServer{stream})
}

type PublishBuildEvent_PublishBuildToolEventStreamServer interface {
	Send(*PublishBuildToolEventStreamResponse) error
	Recv() (*PublishBuildToolEventStreamRequest, error)
	grpc.ServerStream
}

type publishBuildEventPublishBuildToolEventStreamServer struct {
	grpc.ServerStream
}

func (x *publishBuildEventPublishBuildToolEventStreamServer) Send(m *PublishBuildToolEventStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *publishBuildEventPublishBuildToolEventStreamServer) Recv() (*PublishBuildToolEventStreamRequest, error) {
	m := new(PublishBuildToolEventStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PublishBuildEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.devtools.build.v1.PublishBuildEvent",
	HandlerType: (*PublishBuildEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishLifecycleEvent",
			Handler:    _PublishBuildEvent_PublishLifecycleEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishBuildToolEventStream",
			Handler:       _PublishBuildEvent_PublishBuildToolEventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "google/devtools/build/v1/publish_build_event.proto",
}
