// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: google/devtools/build/v1/build_events.proto

package build

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleOutputStream int32

const (
	ConsoleOutputStream_UNKNOWN ConsoleOutputStream = 0
	ConsoleOutputStream_STDOUT  ConsoleOutputStream = 1
	ConsoleOutputStream_STDERR  ConsoleOutputStream = 2
)

// Enum value maps for ConsoleOutputStream.
var (
	ConsoleOutputStream_name = map[int32]string{
		0: "UNKNOWN",
		1: "STDOUT",
		2: "STDERR",
	}
	ConsoleOutputStream_value = map[string]int32{
		"UNKNOWN": 0,
		"STDOUT":  1,
		"STDERR":  2,
	}
)

func (x ConsoleOutputStream) Enum() *ConsoleOutputStream {
	p := new(ConsoleOutputStream)
	*p = x
	return p
}

func (x ConsoleOutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleOutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_google_devtools_build_v1_build_events_proto_enumTypes[0].Descriptor()
}

func (ConsoleOutputStream) Type() protoreflect.EnumType {
	return &file_google_devtools_build_v1_build_events_proto_enumTypes[0]
}

func (x ConsoleOutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleOutputStream.Descriptor instead.
func (ConsoleOutputStream) EnumDescriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0}
}

type BuildEvent_BuildComponentStreamFinished_FinishType int32

const (
	BuildEvent_BuildComponentStreamFinished_FINISH_TYPE_UNSPECIFIED BuildEvent_BuildComponentStreamFinished_FinishType = 0
	BuildEvent_BuildComponentStreamFinished_FINISHED                BuildEvent_BuildComponentStreamFinished_FinishType = 1
	BuildEvent_BuildComponentStreamFinished_EXPIRED                 BuildEvent_BuildComponentStreamFinished_FinishType = 2
)

// Enum value maps for BuildEvent_BuildComponentStreamFinished_FinishType.
var (
	BuildEvent_BuildComponentStreamFinished_FinishType_name = map[int32]string{
		0: "FINISH_TYPE_UNSPECIFIED",
		1: "FINISHED",
		2: "EXPIRED",
	}
	BuildEvent_BuildComponentStreamFinished_FinishType_value = map[string]int32{
		"FINISH_TYPE_UNSPECIFIED": 0,
		"FINISHED":                1,
		"EXPIRED":                 2,
	}
)

func (x BuildEvent_BuildComponentStreamFinished_FinishType) Enum() *BuildEvent_BuildComponentStreamFinished_FinishType {
	p := new(BuildEvent_BuildComponentStreamFinished_FinishType)
	*p = x
	return p
}

func (x BuildEvent_BuildComponentStreamFinished_FinishType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildEvent_BuildComponentStreamFinished_FinishType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_devtools_build_v1_build_events_proto_enumTypes[1].Descriptor()
}

func (BuildEvent_BuildComponentStreamFinished_FinishType) Type() protoreflect.EnumType {
	return &file_google_devtools_build_v1_build_events_proto_enumTypes[1]
}

func (x BuildEvent_BuildComponentStreamFinished_FinishType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildEvent_BuildComponentStreamFinished_FinishType.Descriptor instead.
func (BuildEvent_BuildComponentStreamFinished_FinishType) EnumDescriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 5, 0}
}

type StreamId_BuildComponent int32

const (
	StreamId_UNKNOWN_COMPONENT StreamId_BuildComponent = 0
	StreamId_CONTROLLER        StreamId_BuildComponent = 1
	StreamId_WORKER            StreamId_BuildComponent = 2
	StreamId_TOOL              StreamId_BuildComponent = 3
)

// Enum value maps for StreamId_BuildComponent.
var (
	StreamId_BuildComponent_name = map[int32]string{
		0: "UNKNOWN_COMPONENT",
		1: "CONTROLLER",
		2: "WORKER",
		3: "TOOL",
	}
	StreamId_BuildComponent_value = map[string]int32{
		"UNKNOWN_COMPONENT": 0,
		"CONTROLLER":        1,
		"WORKER":            2,
		"TOOL":              3,
	}
)

func (x StreamId_BuildComponent) Enum() *StreamId_BuildComponent {
	p := new(StreamId_BuildComponent)
	*p = x
	return p
}

func (x StreamId_BuildComponent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamId_BuildComponent) Descriptor() protoreflect.EnumDescriptor {
	return file_google_devtools_build_v1_build_events_proto_enumTypes[2].Descriptor()
}

func (StreamId_BuildComponent) Type() protoreflect.EnumType {
	return &file_google_devtools_build_v1_build_events_proto_enumTypes[2]
}

func (x StreamId_BuildComponent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamId_BuildComponent.Descriptor instead.
func (StreamId_BuildComponent) EnumDescriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{1, 0}
}

type BuildEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*BuildEvent_InvocationAttemptStarted_
	//	*BuildEvent_InvocationAttemptFinished_
	//	*BuildEvent_BuildEnqueued_
	//	*BuildEvent_BuildFinished_
	//	*BuildEvent_ConsoleOutput_
	//	*BuildEvent_ComponentStreamFinished
	//	*BuildEvent_BazelEvent
	//	*BuildEvent_BuildExecutionEvent
	//	*BuildEvent_SourceFetchEvent
	Event         isBuildEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0}
}

func (x *BuildEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *BuildEvent) GetEvent() isBuildEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BuildEvent) GetInvocationAttemptStarted() *BuildEvent_InvocationAttemptStarted {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_InvocationAttemptStarted_); ok {
			return x.InvocationAttemptStarted
		}
	}
	return nil
}

func (x *BuildEvent) GetInvocationAttemptFinished() *BuildEvent_InvocationAttemptFinished {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_InvocationAttemptFinished_); ok {
			return x.InvocationAttemptFinished
		}
	}
	return nil
}

func (x *BuildEvent) GetBuildEnqueued() *BuildEvent_BuildEnqueued {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_BuildEnqueued_); ok {
			return x.BuildEnqueued
		}
	}
	return nil
}

func (x *BuildEvent) GetBuildFinished() *BuildEvent_BuildFinished {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_BuildFinished_); ok {
			return x.BuildFinished
		}
	}
	return nil
}

func (x *BuildEvent) GetConsoleOutput() *BuildEvent_ConsoleOutput {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_ConsoleOutput_); ok {
			return x.ConsoleOutput
		}
	}
	return nil
}

func (x *BuildEvent) GetComponentStreamFinished() *BuildEvent_BuildComponentStreamFinished {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_ComponentStreamFinished); ok {
			return x.ComponentStreamFinished
		}
	}
	return nil
}

func (x *BuildEvent) GetBazelEvent() *anypb.Any {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_BazelEvent); ok {
			return x.BazelEvent
		}
	}
	return nil
}

func (x *BuildEvent) GetBuildExecutionEvent() *anypb.Any {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_BuildExecutionEvent); ok {
			return x.BuildExecutionEvent
		}
	}
	return nil
}

func (x *BuildEvent) GetSourceFetchEvent() *anypb.Any {
	if x != nil {
		if x, ok := x.Event.(*BuildEvent_SourceFetchEvent); ok {
			return x.SourceFetchEvent
		}
	}
	return nil
}

type isBuildEvent_Event interface {
	isBuildEvent_Event()
}

type BuildEvent_InvocationAttemptStarted_ struct {
	InvocationAttemptStarted *BuildEvent_InvocationAttemptStarted `protobuf:"bytes,51,opt,name=invocation_attempt_started,json=invocationAttemptStarted,proto3,oneof"`
}

type BuildEvent_InvocationAttemptFinished_ struct {
	InvocationAttemptFinished *BuildEvent_InvocationAttemptFinished `protobuf:"bytes,52,opt,name=invocation_attempt_finished,json=invocationAttemptFinished,proto3,oneof"`
}

type BuildEvent_BuildEnqueued_ struct {
	BuildEnqueued *BuildEvent_BuildEnqueued `protobuf:"bytes,53,opt,name=build_enqueued,json=buildEnqueued,proto3,oneof"`
}

type BuildEvent_BuildFinished_ struct {
	BuildFinished *BuildEvent_BuildFinished `protobuf:"bytes,55,opt,name=build_finished,json=buildFinished,proto3,oneof"`
}

type BuildEvent_ConsoleOutput_ struct {
	ConsoleOutput *BuildEvent_ConsoleOutput `protobuf:"bytes,56,opt,name=console_output,json=consoleOutput,proto3,oneof"`
}

type BuildEvent_ComponentStreamFinished struct {
	ComponentStreamFinished *BuildEvent_BuildComponentStreamFinished `protobuf:"bytes,59,opt,name=component_stream_finished,json=componentStreamFinished,proto3,oneof"`
}

type BuildEvent_BazelEvent struct {
	BazelEvent *anypb.Any `protobuf:"bytes,60,opt,name=bazel_event,json=bazelEvent,proto3,oneof"`
}

type BuildEvent_BuildExecutionEvent struct {
	BuildExecutionEvent *anypb.Any `protobuf:"bytes,61,opt,name=build_execution_event,json=buildExecutionEvent,proto3,oneof"`
}

type BuildEvent_SourceFetchEvent struct {
	SourceFetchEvent *anypb.Any `protobuf:"bytes,62,opt,name=source_fetch_event,json=sourceFetchEvent,proto3,oneof"`
}

func (*BuildEvent_InvocationAttemptStarted_) isBuildEvent_Event() {}

func (*BuildEvent_InvocationAttemptFinished_) isBuildEvent_Event() {}

func (*BuildEvent_BuildEnqueued_) isBuildEvent_Event() {}

func (*BuildEvent_BuildFinished_) isBuildEvent_Event() {}

func (*BuildEvent_ConsoleOutput_) isBuildEvent_Event() {}

func (*BuildEvent_ComponentStreamFinished) isBuildEvent_Event() {}

func (*BuildEvent_BazelEvent) isBuildEvent_Event() {}

func (*BuildEvent_BuildExecutionEvent) isBuildEvent_Event() {}

func (*BuildEvent_SourceFetchEvent) isBuildEvent_Event() {}

type StreamId struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BuildId       string                  `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	InvocationId  string                  `protobuf:"bytes,6,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Component     StreamId_BuildComponent `protobuf:"varint,3,opt,name=component,proto3,enum=google.devtools.build.v1.StreamId_BuildComponent" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamId) Reset() {
	*x = StreamId{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamId) ProtoMessage() {}

func (x *StreamId) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamId.ProtoReflect.Descriptor instead.
func (*StreamId) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{1}
}

func (x *StreamId) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StreamId) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *StreamId) GetComponent() StreamId_BuildComponent {
	if x != nil {
		return x.Component
	}
	return StreamId_UNKNOWN_COMPONENT
}

type BuildEvent_InvocationAttemptStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptNumber int64                  `protobuf:"varint,1,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Details       *anypb.Any             `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent_InvocationAttemptStarted) Reset() {
	*x = BuildEvent_InvocationAttemptStarted{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_InvocationAttemptStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_InvocationAttemptStarted) ProtoMessage() {}

func (x *BuildEvent_InvocationAttemptStarted) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_InvocationAttemptStarted.ProtoReflect.Descriptor instead.
func (*BuildEvent_InvocationAttemptStarted) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BuildEvent_InvocationAttemptStarted) GetAttemptNumber() int64 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *BuildEvent_InvocationAttemptStarted) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type BuildEvent_InvocationAttemptFinished struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvocationStatus *BuildStatus           `protobuf:"bytes,3,opt,name=invocation_status,json=invocationStatus,proto3" json:"invocation_status,omitempty"`
	Details          *anypb.Any             `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildEvent_InvocationAttemptFinished) Reset() {
	*x = BuildEvent_InvocationAttemptFinished{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_InvocationAttemptFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_InvocationAttemptFinished) ProtoMessage() {}

func (x *BuildEvent_InvocationAttemptFinished) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_InvocationAttemptFinished.ProtoReflect.Descriptor instead.
func (*BuildEvent_InvocationAttemptFinished) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BuildEvent_InvocationAttemptFinished) GetInvocationStatus() *BuildStatus {
	if x != nil {
		return x.InvocationStatus
	}
	return nil
}

func (x *BuildEvent_InvocationAttemptFinished) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type BuildEvent_BuildEnqueued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *anypb.Any             `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent_BuildEnqueued) Reset() {
	*x = BuildEvent_BuildEnqueued{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_BuildEnqueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_BuildEnqueued) ProtoMessage() {}

func (x *BuildEvent_BuildEnqueued) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_BuildEnqueued.ProtoReflect.Descriptor instead.
func (*BuildEvent_BuildEnqueued) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 2}
}

func (x *BuildEvent_BuildEnqueued) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type BuildEvent_BuildFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *BuildStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       *anypb.Any             `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent_BuildFinished) Reset() {
	*x = BuildEvent_BuildFinished{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_BuildFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_BuildFinished) ProtoMessage() {}

func (x *BuildEvent_BuildFinished) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_BuildFinished.ProtoReflect.Descriptor instead.
func (*BuildEvent_BuildFinished) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 3}
}

func (x *BuildEvent_BuildFinished) GetStatus() *BuildStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BuildEvent_BuildFinished) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type BuildEvent_ConsoleOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ConsoleOutputStream    `protobuf:"varint,1,opt,name=type,proto3,enum=google.devtools.build.v1.ConsoleOutputStream" json:"type,omitempty"`
	// Types that are valid to be assigned to Output:
	//
	//	*BuildEvent_ConsoleOutput_TextOutput
	//	*BuildEvent_ConsoleOutput_BinaryOutput
	Output        isBuildEvent_ConsoleOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent_ConsoleOutput) Reset() {
	*x = BuildEvent_ConsoleOutput{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_ConsoleOutput) ProtoMessage() {}

func (x *BuildEvent_ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_ConsoleOutput.ProtoReflect.Descriptor instead.
func (*BuildEvent_ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 4}
}

func (x *BuildEvent_ConsoleOutput) GetType() ConsoleOutputStream {
	if x != nil {
		return x.Type
	}
	return ConsoleOutputStream_UNKNOWN
}

func (x *BuildEvent_ConsoleOutput) GetOutput() isBuildEvent_ConsoleOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *BuildEvent_ConsoleOutput) GetTextOutput() string {
	if x != nil {
		if x, ok := x.Output.(*BuildEvent_ConsoleOutput_TextOutput); ok {
			return x.TextOutput
		}
	}
	return ""
}

func (x *BuildEvent_ConsoleOutput) GetBinaryOutput() []byte {
	if x != nil {
		if x, ok := x.Output.(*BuildEvent_ConsoleOutput_BinaryOutput); ok {
			return x.BinaryOutput
		}
	}
	return nil
}

type isBuildEvent_ConsoleOutput_Output interface {
	isBuildEvent_ConsoleOutput_Output()
}

type BuildEvent_ConsoleOutput_TextOutput struct {
	TextOutput string `protobuf:"bytes,2,opt,name=text_output,json=textOutput,proto3,oneof"`
}

type BuildEvent_ConsoleOutput_BinaryOutput struct {
	BinaryOutput []byte `protobuf:"bytes,3,opt,name=binary_output,json=binaryOutput,proto3,oneof"`
}

func (*BuildEvent_ConsoleOutput_TextOutput) isBuildEvent_ConsoleOutput_Output() {}

func (*BuildEvent_ConsoleOutput_BinaryOutput) isBuildEvent_ConsoleOutput_Output() {}

type BuildEvent_BuildComponentStreamFinished struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Type          BuildEvent_BuildComponentStreamFinished_FinishType `protobuf:"varint,1,opt,name=type,proto3,enum=google.devtools.build.v1.BuildEvent_BuildComponentStreamFinished_FinishType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent_BuildComponentStreamFinished) Reset() {
	*x = BuildEvent_BuildComponentStreamFinished{}
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent_BuildComponentStreamFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent_BuildComponentStreamFinished) ProtoMessage() {}

func (x *BuildEvent_BuildComponentStreamFinished) ProtoReflect() protoreflect.Message {
	mi := &file_google_devtools_build_v1_build_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent_BuildComponentStreamFinished.ProtoReflect.Descriptor instead.
func (*BuildEvent_BuildComponentStreamFinished) Descriptor() ([]byte, []int) {
	return file_google_devtools_build_v1_build_events_proto_rawDescGZIP(), []int{0, 5}
}

func (x *BuildEvent_BuildComponentStreamFinished) GetType() BuildEvent_BuildComponentStreamFinished_FinishType {
	if x != nil {
		return x.Type
	}
	return BuildEvent_BuildComponentStreamFinished_FINISH_TYPE_UNSPECIFIED
}

var File_google_devtools_build_v1_build_events_proto protoreflect.FileDescriptor

const file_google_devtools_build_v1_build_events_proto_rawDesc = "" +
	"\n" +
	"+google/devtools/build/v1/build_events.proto\x12\x18google.devtools.build.v1\x1a+google/devtools/build/v1/build_status.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\r\n" +
	"\n" +
	"BuildEvent\x129\n" +
	"\n" +
	"event_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12}\n" +
	"\x1ainvocation_attempt_started\x183 \x01(\v2=.google.devtools.build.v1.BuildEvent.InvocationAttemptStartedH\x00R\x18invocationAttemptStarted\x12\x80\x01\n" +
	"\x1binvocation_attempt_finished\x184 \x01(\v2>.google.devtools.build.v1.BuildEvent.InvocationAttemptFinishedH\x00R\x19invocationAttemptFinished\x12[\n" +
	"\x0ebuild_enqueued\x185 \x01(\v22.google.devtools.build.v1.BuildEvent.BuildEnqueuedH\x00R\rbuildEnqueued\x12[\n" +
	"\x0ebuild_finished\x187 \x01(\v22.google.devtools.build.v1.BuildEvent.BuildFinishedH\x00R\rbuildFinished\x12[\n" +
	"\x0econsole_output\x188 \x01(\v22.google.devtools.build.v1.BuildEvent.ConsoleOutputH\x00R\rconsoleOutput\x12\x7f\n" +
	"\x19component_stream_finished\x18; \x01(\v2A.google.devtools.build.v1.BuildEvent.BuildComponentStreamFinishedH\x00R\x17componentStreamFinished\x127\n" +
	"\vbazel_event\x18< \x01(\v2\x14.google.protobuf.AnyH\x00R\n" +
	"bazelEvent\x12J\n" +
	"\x15build_execution_event\x18= \x01(\v2\x14.google.protobuf.AnyH\x00R\x13buildExecutionEvent\x12D\n" +
	"\x12source_fetch_event\x18> \x01(\v2\x14.google.protobuf.AnyH\x00R\x10sourceFetchEvent\x1aq\n" +
	"\x18InvocationAttemptStarted\x12%\n" +
	"\x0eattempt_number\x18\x01 \x01(\x03R\rattemptNumber\x12.\n" +
	"\adetails\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\adetails\x1a\x9f\x01\n" +
	"\x19InvocationAttemptFinished\x12R\n" +
	"\x11invocation_status\x18\x03 \x01(\v2%.google.devtools.build.v1.BuildStatusR\x10invocationStatus\x12.\n" +
	"\adetails\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\adetails\x1a?\n" +
	"\rBuildEnqueued\x12.\n" +
	"\adetails\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\adetails\x1a~\n" +
	"\rBuildFinished\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.google.devtools.build.v1.BuildStatusR\x06status\x12.\n" +
	"\adetails\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\adetails\x1a\xa6\x01\n" +
	"\rConsoleOutput\x12A\n" +
	"\x04type\x18\x01 \x01(\x0e2-.google.devtools.build.v1.ConsoleOutputStreamR\x04type\x12!\n" +
	"\vtext_output\x18\x02 \x01(\tH\x00R\n" +
	"textOutput\x12%\n" +
	"\rbinary_output\x18\x03 \x01(\fH\x00R\fbinaryOutputB\b\n" +
	"\x06output\x1a\xc6\x01\n" +
	"\x1cBuildComponentStreamFinished\x12`\n" +
	"\x04type\x18\x01 \x01(\x0e2L.google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished.FinishTypeR\x04type\"D\n" +
	"\n" +
	"FinishType\x12\x1b\n" +
	"\x17FINISH_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bFINISHED\x10\x01\x12\v\n" +
	"\aEXPIRED\x10\x02B\a\n" +
	"\x05event\"\xea\x01\n" +
	"\bStreamId\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12#\n" +
	"\rinvocation_id\x18\x06 \x01(\tR\finvocationId\x12O\n" +
	"\tcomponent\x18\x03 \x01(\x0e21.google.devtools.build.v1.StreamId.BuildComponentR\tcomponent\"M\n" +
	"\x0eBuildComponent\x12\x15\n" +
	"\x11UNKNOWN_COMPONENT\x10\x00\x12\x0e\n" +
	"\n" +
	"CONTROLLER\x10\x01\x12\n" +
	"\n" +
	"\x06WORKER\x10\x02\x12\b\n" +
	"\x04TOOL\x10\x03*:\n" +
	"\x13ConsoleOutputStream\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02B\x8b\x01\n" +
	"\x1ccom.google.devtools.build.v1B\x0fBuildEventProtoP\x01Z=google.golang.org/genproto/googleapis/devtools/build/v1;build\xf8\x01\x01\xca\x02\x15Google\\Cloud\\Build\\V1b\x06proto3"

var (
	file_google_devtools_build_v1_build_events_proto_rawDescOnce sync.Once
	file_google_devtools_build_v1_build_events_proto_rawDescData []byte
)

func file_google_devtools_build_v1_build_events_proto_rawDescGZIP() []byte {
	file_google_devtools_build_v1_build_events_proto_rawDescOnce.Do(func() {
		file_google_devtools_build_v1_build_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_devtools_build_v1_build_events_proto_rawDesc), len(file_google_devtools_build_v1_build_events_proto_rawDesc)))
	})
	return file_google_devtools_build_v1_build_events_proto_rawDescData
}

var file_google_devtools_build_v1_build_events_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_google_devtools_build_v1_build_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_google_devtools_build_v1_build_events_proto_goTypes = []any{
	(ConsoleOutputStream)(0),                                // 0: google.devtools.build.v1.ConsoleOutputStream
	(BuildEvent_BuildComponentStreamFinished_FinishType)(0), // 1: google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished.FinishType
	(StreamId_BuildComponent)(0),                            // 2: google.devtools.build.v1.StreamId.BuildComponent
	(*BuildEvent)(nil),                                      // 3: google.devtools.build.v1.BuildEvent
	(*StreamId)(nil),                                        // 4: google.devtools.build.v1.StreamId
	(*BuildEvent_InvocationAttemptStarted)(nil),             // 5: google.devtools.build.v1.BuildEvent.InvocationAttemptStarted
	(*BuildEvent_InvocationAttemptFinished)(nil),            // 6: google.devtools.build.v1.BuildEvent.InvocationAttemptFinished
	(*BuildEvent_BuildEnqueued)(nil),                        // 7: google.devtools.build.v1.BuildEvent.BuildEnqueued
	(*BuildEvent_BuildFinished)(nil),                        // 8: google.devtools.build.v1.BuildEvent.BuildFinished
	(*BuildEvent_ConsoleOutput)(nil),                        // 9: google.devtools.build.v1.BuildEvent.ConsoleOutput
	(*BuildEvent_BuildComponentStreamFinished)(nil),         // 10: google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished
	(*timestamppb.Timestamp)(nil),                           // 11: google.protobuf.Timestamp
	(*anypb.Any)(nil),                                       // 12: google.protobuf.Any
	(*BuildStatus)(nil),                                     // 13: google.devtools.build.v1.BuildStatus
}
var file_google_devtools_build_v1_build_events_proto_depIdxs = []int32{
	11, // 0: google.devtools.build.v1.BuildEvent.event_time:type_name -> google.protobuf.Timestamp
	5,  // 1: google.devtools.build.v1.BuildEvent.invocation_attempt_started:type_name -> google.devtools.build.v1.BuildEvent.InvocationAttemptStarted
	6,  // 2: google.devtools.build.v1.BuildEvent.invocation_attempt_finished:type_name -> google.devtools.build.v1.BuildEvent.InvocationAttemptFinished
	7,  // 3: google.devtools.build.v1.BuildEvent.build_enqueued:type_name -> google.devtools.build.v1.BuildEvent.BuildEnqueued
	8,  // 4: google.devtools.build.v1.BuildEvent.build_finished:type_name -> google.devtools.build.v1.BuildEvent.BuildFinished
	9,  // 5: google.devtools.build.v1.BuildEvent.console_output:type_name -> google.devtools.build.v1.BuildEvent.ConsoleOutput
	10, // 6: google.devtools.build.v1.BuildEvent.component_stream_finished:type_name -> google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished
	12, // 7: google.devtools.build.v1.BuildEvent.bazel_event:type_name -> google.protobuf.Any
	12, // 8: google.devtools.build.v1.BuildEvent.build_execution_event:type_name -> google.protobuf.Any
	12, // 9: google.devtools.build.v1.BuildEvent.source_fetch_event:type_name -> google.protobuf.Any
	2,  // 10: google.devtools.build.v1.StreamId.component:type_name -> google.devtools.build.v1.StreamId.BuildComponent
	12, // 11: google.devtools.build.v1.BuildEvent.InvocationAttemptStarted.details:type_name -> google.protobuf.Any
	13, // 12: google.devtools.build.v1.BuildEvent.InvocationAttemptFinished.invocation_status:type_name -> google.devtools.build.v1.BuildStatus
	12, // 13: google.devtools.build.v1.BuildEvent.InvocationAttemptFinished.details:type_name -> google.protobuf.Any
	12, // 14: google.devtools.build.v1.BuildEvent.BuildEnqueued.details:type_name -> google.protobuf.Any
	13, // 15: google.devtools.build.v1.BuildEvent.BuildFinished.status:type_name -> google.devtools.build.v1.BuildStatus
	12, // 16: google.devtools.build.v1.BuildEvent.BuildFinished.details:type_name -> google.protobuf.Any
	0,  // 17: google.devtools.build.v1.BuildEvent.ConsoleOutput.type:type_name -> google.devtools.build.v1.ConsoleOutputStream
	1,  // 18: google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished.type:type_name -> google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished.FinishType
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_google_devtools_build_v1_build_events_proto_init() }
func file_google_devtools_build_v1_build_events_proto_init() {
	if File_google_devtools_build_v1_build_events_proto != nil {
		return
	}
	file_google_devtools_build_v1_build_status_proto_init()
	file_google_devtools_build_v1_build_events_proto_msgTypes[0].OneofWrappers = []any{
		(*BuildEvent_InvocationAttemptStarted_)(nil),
		(*BuildEvent_InvocationAttemptFinished_)(nil),
		(*BuildEvent_BuildEnqueued_)(nil),
		(*BuildEvent_BuildFinished_)(nil),
		(*BuildEvent_ConsoleOutput_)(nil),
		(*BuildEvent_ComponentStreamFinished)(nil),
		(*BuildEvent_BazelEvent)(nil),
		(*BuildEvent_BuildExecutionEvent)(nil),
		(*BuildEvent_SourceFetchEvent)(nil),
	}
	file_google_devtools_build_v1_build_events_proto_msgTypes[6].OneofWrappers = []any{
		(*BuildEvent_ConsoleOutput_TextOutput)(nil),
		(*BuildEvent_ConsoleOutput_BinaryOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_devtools_build_v1_build_events_proto_rawDesc), len(file_google_devtools_build_v1_build_events_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_devtools_build_v1_build_events_proto_goTypes,
		DependencyIndexes: file_google_devtools_build_v1_build_events_proto_depIdxs,
		EnumInfos:         file_google_devtools_build_v1_build_events_proto_enumTypes,
		MessageInfos:      file_google_devtools_build_v1_build_events_proto_msgTypes,
	}.Build()
	File_google_devtools_build_v1_build_events_proto = out.File
	file_google_devtools_build_v1_build_events_proto_goTypes = nil
	file_google_devtools_build_v1_build_events_proto_depIdxs = nil
}
